on:
  push:
    branches:
    - deploy
  release:
    types: [publish]
    
jobs:
  setup-env:
    name: Setup Env
    runs-on: ubuntu-latest
  
    steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm test
    
    - name: Install SSH key of bastion
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa-bastion
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        config: |
          Host bastion
            HostName {{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USER }}
            Port 22
            IdentityFile ~/.ssh/id_rsa-bastion
  
    - name: Check ssh key
      run: ssh bastion
       

  
