on:
  push:
    branches:
    - deploy
  release:
    types: [publish]
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm test
