on:
  push:
    branches:
    - deploy
  release:
    types: [publish]
    
jobs:
  setup-env:
    name: Setup Env
    runs-on: ubuntu-latest
  
    steps: 
#     - uses: actions/checkout@v3
#     - uses: actions/setup-node@v3
#       with:
#         node-version: 16
#         cache: 'npm'
#     - run: npm ci
#     - run: npm test
    
    - name: Install SSH key of bastion
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} " ls "
#       run: ls 
      
       

  
